## Import Needed Package

In [1]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings("ignore")

## Load Dataset

In [2]:
data = pd.read_csv("./IMDB_Dataset.csv")

In [3]:
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
data["sentiment"].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

# One Hot Encoding

## Label Encoder

In [5]:
data.replace({"sentiment":{"positive": 1, "negative": 0}}, inplace=True)

In [6]:
data.head()

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

# Data Preprocessing

In [9]:
pip install tensorflow

Requirement already satisfied: tensorflow in d:\anaconda3\envs\lab_ai\lib\site-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (2.3.1)
Requirement already satisfied: astunparse>=1.6.0 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (25.9.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google_pasta>=0.1.1 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf>=5.28.0 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (6.32.1)
Requirement already satisfied: requests<3,>=2.21.0 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (78.1.1)
Requirement already satisfied: six>=1.12.0 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing_extensions>=3.6.6 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (1.17.3)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (1.76.0)
Requirement already satisfied: tensorboard~=2.20.0 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (3.12.0)
Requirement already satisfied: numpy>=1.26.0 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (2.1.2)
Requirement already satisfied: h5py>=3.11.0 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorflow) (0.5.3)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\anaconda3\envs\lab_ai\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda3\envs\lab_ai\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda3\envs\lab_ai\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda3\envs\lab_ai\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.8.3)
Requirement already satisfied: markdown>=2.6.8 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.10)
Requirement already satisfied: pillow in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (11.0.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in d:\anaconda3\envs\lab_ai\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.1.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in d:\anaconda3\envs\lab_ai\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in d:\anaconda3\envs\lab_ai\lib\site-packages (from keras>=3.10.0->tensorflow) (14.1.0)
Requirement already satisfied: namex in d:\anaconda3\envs\lab_ai\lib\site-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in d:\anaconda3\envs\lab_ai\lib\site-packages (from keras>=3.10.0->tensorflow) (0.17.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in d:\anaconda3\envs\lab_ai\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (2.1.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in d:\anaconda3\envs\lab_ai\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in d:\anaconda3\envs\lab_ai\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in d:\anaconda3\envs\lab_ai\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [11]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [12]:
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

In [14]:
train_data.shape

(40000, 2)

In [15]:
test_data.shape

(10000, 2)

In [16]:
tokenizer = Tokenizer(num_words = 5000)
tokenizer.fit_on_texts(train_data["review"])

In [23]:
X_train = pad_sequences(tokenizer.texts_to_sequences(train_data["review"]), maxlen=200)
X_test = pad_sequences(tokenizer.texts_to_sequences(test_data["review"]), maxlen=200)

In [24]:
X_train

array([[1935,    1, 1200, ...,  205,  351, 3856],
       [   3, 1651,  595, ...,   89,  103,    9],
       [   0,    0,    0, ...,    2,  710,   62],
       ...,
       [   0,    0,    0, ..., 1641,    2,  603],
       [   0,    0,    0, ...,  245,  103,  125],
       [   0,    0,    0, ...,   70,   73, 2062]], dtype=int32)

In [25]:
X_test

array([[   0,    0,    0, ...,  995,  719,  155],
       [  12,  162,   59, ...,  380,    7,    7],
       [   0,    0,    0, ...,   50, 1088,   96],
       ...,
       [   0,    0,    0, ...,  125,  200, 3241],
       [   0,    0,    0, ..., 1066,    1, 2305],
       [   0,    0,    0, ...,    1,  332,   27]], dtype=int32)

In [26]:
Y_train = train_data["sentiment"]
Y_test = test_data["sentiment"]

In [27]:
Y_train

39087    0
30893    0
45278    1
16398    0
13653    0
        ..
11284    1
44732    1
38158    0
860      1
15795    1
Name: sentiment, Length: 40000, dtype: int64

In [28]:
Y_test

33553    1
9427     1
199      0
12447    1
39489    0
        ..
28567    0
25079    1
18707    1
15200    0
5857     1
Name: sentiment, Length: 10000, dtype: int64

# Model Building

In [30]:
model = Sequential()
model.add(Embedding(input_dim = 5000, output_dim = 128, input_length = 200))
model.add(LSTM(128, dropout=0.2, recurrent_dropout = 0.2))
model.add(Dense(1, activation = "sigmoid"))

In [31]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.compile(optimizer = "adam",loss="binary_crossentropy", metrics=["accuracy"])

In [33]:
model.fit(X_train, Y_train, epochs = 5, batch_size = 64, validation_split = 0.2)

Epoch 1/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 354s 700ms/step - accuracy: 0.7857 - loss: 0.4635 - val_accuracy: 0.8508 - val_loss: 0.3502
Epoch 2/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 372s 744ms/step - accuracy: 0.8351 - loss: 0.3924 - val_accuracy: 0.8443 - val_loss: 0.3623
Epoch 3/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 362s 723ms/step - accuracy: 0.8712 - loss: 0.3170 - val_accuracy: 0.8618 - val_loss: 0.3345
Epoch 4/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 359s 717ms/step - accuracy: 0.8881 - loss: 0.2838 - val_accuracy: 0.8741 - val_loss: 0.3085
Epoch 5/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 369s 737ms/step - accuracy: 0.9052 - loss: 0.2444 - val_accuracy: 0.8749 - val_loss: 0.3361

In [34]:
loss, accuracy = model.evaluate (X_test, Y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 23s 71ms/step - accuracy: 0.8774 - loss: 0.3338

In [35]:
print(loss)

0.3338111937046051

In [36]:
print(accuracy)

0.8773999810218811

# Building Predictive System

In [37]:
def predictive_system(review):
    sequences = tokenizer.texts_to_sequences([review])
    padded_sequence = pad_sequences(sequences, maxlen=200)
    prediction = model.predict(padded_sequence)
    sentiment = "positive" if prediction[0][0] > 0.5 else "negative"
    return sentiment

In [38]:
predictive_system("This movie was fantastic and amazing")

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 632ms/step

'positive'

In [39]:
predictive_system("A trilling adventure with stunning visual")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step

'positive'

In [40]:
predictive_system("A visual masterpiece")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step

'positive'

In [41]:
predictive_system("Overall long and slow")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

'negative'

# Saving Model

In [42]:
model.save("model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [43]:
import joblib
joblib.dump(tokenizer, "tokenizer.pkl")

['tokenizer.pkl']